package cz.ardno.itemshuffle.enumerators;

import org.bukkit.Material;

import java.util.ArrayList;
import java.util.List;

public class AvailableItems { //backup

    public static final List<Material> items = new ArrayList<>();

    public static List<Material> getItems() {
        return items;
    }

    static { //1.16 things
        //region Building Blocks
//        items.add(Material.IRON_ORE);
//        items.add(Material.COAL_ORE); SILK
//        items.add(Material.NETHER_GOLD_ORE); SILK
//        items.add(Material.OAK_LOG);
//        items.add(Material.SPRUCE_LOG);
//        items.add(Material.BIRCH_LOG);
//        items.add(Material.JUNGLE_LOG);
//        items.add(Material.ACACIA_LOG);
//        items.add(Material.DARK_OAK_LOG);
//        items.add(Material.STONE);
//        items.add(Material.GRANITE);
//        items.add(Material.POLISHED_GRANITE);
//        items.add(Material.DIORITE);
//        items.add(Material.POLISHED_DIORITE);
//        items.add(Material.ANDESITE);
//        items.add(Material.POLISHED_ANDESITE);
//        items.add(Material.GRASS_BLOCK); SILK
//        items.add(Material.DIRT);
//        items.add(Material.COARSE_DIRT);
//        items.add(Material.PODZOL);
//        items.add(Material.CRIMSON_NYLIUM); SILK
//        items.add(Material.WARPED_NYLIUM); SILK
//        items.add(Material.COBBLESTONE);
//        items.add(Material.OAK_PLANKS);
//        items.add(Material.SPRUCE_PLANKS);
//        items.add(Material.BIRCH_PLANKS);
//        items.add(Material.JUNGLE_PLANKS);
//        items.add(Material.ACACIA_PLANKS);
//        items.add(Material.DARK_OAK_PLANKS);
//        items.add(Material.CRIMSON_PLANKS);
//        items.add(Material.WARPED_PLANKS);
//        items.add(Material.SAND);
//        items.add(Material.RED_SAND);
//        items.add(Material.GRAVEL);
//        items.add(Material.GOLD_ORE);
//        items.add(Material.WET_SPONGE);
//        items.add(Material.GLASS);
//        items.add(Material.LAPIS_ORE);
//        items.add(Material.LAPIS_BLOCK);
//        items.add(Material.SANDSTONE);
//        items.add(Material.CHISELED_SANDSTONE);
//        items.add(Material.CUT_SANDSTONE);
//        items.add(Material.WHITE_WOOL);
//        items.add(Material.ORANGE_WOOL);
//        items.add(Material.CRIMSON_STEM);
//        items.add(Material.WARPED_STEM);
//        items.add(Material.STRIPPED_OAK_LOG);
//        items.add(Material.STRIPPED_SPRUCE_LOG);
//        items.add(Material.STRIPPED_BIRCH_LOG);
//        items.add(Material.STRIPPED_JUNGLE_LOG);
//        items.add(Material.STRIPPED_ACACIA_LOG);
//        items.add(Material.STRIPPED_DARK_OAK_LOG);
//        items.add(Material.STRIPPED_CRIMSON_STEM);
//        items.add(Material.STRIPPED_WARPED_STEM);
//        items.add(Material.STRIPPED_OAK_WOOD);
//        items.add(Material.STRIPPED_SPRUCE_WOOD);
//        items.add(Material.STRIPPED_BIRCH_WOOD);
//        items.add(Material.STRIPPED_JUNGLE_WOOD);
//        items.add(Material.STRIPPED_ACACIA_WOOD);
//        items.add(Material.STRIPPED_DARK_OAK_WOOD);
//        items.add(Material.STRIPPED_CRIMSON_HYPHAE);
//        items.add(Material.STRIPPED_WARPED_HYPHAE);
//        items.add(Material.OAK_WOOD);
//        items.add(Material.SPRUCE_WOOD);
//        items.add(Material.BIRCH_WOOD);
//        items.add(Material.JUNGLE_WOOD);
//        items.add(Material.ACACIA_WOOD);
//        items.add(Material.DARK_OAK_WOOD);
//        items.add(Material.CRIMSON_HYPHAE);
//        items.add(Material.WARPED_HYPHAE);
//        items.add(Material.SPONGE);
//        items.add(Material.CUT_SANDSTONE_SLAB);
//        items.add(Material.COBBLESTONE_SLAB);
//        items.add(Material.BRICK_SLAB);
//        items.add(Material.STONE_BRICK_SLAB);
//        items.add(Material.NETHER_BRICK_SLAB);
//        items.add(Material.QUARTZ_SLAB);
//        items.add(Material.RED_SANDSTONE_SLAB);
//        items.add(Material.CUT_RED_SANDSTONE_SLAB);
//        items.add(Material.MAGENTA_WOOL);
//        items.add(Material.LIGHT_BLUE_WOOL);
//        items.add(Material.YELLOW_WOOL);
//        items.add(Material.LIME_WOOL);
//        items.add(Material.PINK_WOOL);
//        items.add(Material.GRAY_WOOL);
//        items.add(Material.LIGHT_GRAY_WOOL);
//        items.add(Material.CYAN_WOOL);
//        items.add(Material.PURPLE_WOOL);
//        items.add(Material.BLUE_WOOL);
//        items.add(Material.BROWN_WOOL);
//        items.add(Material.GREEN_WOOL);
//        items.add(Material.RED_WOOL);
//        items.add(Material.BLACK_WOOL);
//        items.add(Material.GOLD_BLOCK);
//        items.add(Material.IRON_BLOCK);
//        items.add(Material.OAK_SLAB);
//        items.add(Material.SPRUCE_SLAB);
//        items.add(Material.BIRCH_SLAB);
//        items.add(Material.JUNGLE_SLAB);
//        items.add(Material.ACACIA_SLAB);
//        items.add(Material.DARK_OAK_SLAB);
//        items.add(Material.CRIMSON_SLAB);
//        items.add(Material.WARPED_SLAB);
//        items.add(Material.STONE_SLAB);
//        items.add(Material.SMOOTH_STONE_SLAB);
//        items.add(Material.SANDSTONE_SLAB);
//        items.add(Material.SOUL_SOIL);
//        items.add(Material.BASALT);
//        items.add(Material.POLISHED_BASALT);
//        items.add(Material.GLOWSTONE);
//        items.add(Material.JACK_O_LANTERN);
//        items.add(Material.STONE_BRICKS);
//        items.add(Material.MOSSY_STONE_BRICKS);
//        items.add(Material.CRACKED_STONE_BRICKS);
//        items.add(Material.CHISELED_STONE_BRICKS);
//        items.add(Material.PURPUR_SLAB);
//        items.add(Material.PRISMARINE_SLAB);
//        items.add(Material.PRISMARINE_BRICK_SLAB);
//        items.add(Material.DARK_PRISMARINE_SLAB);
//        items.add(Material.SMOOTH_QUARTZ);
//        items.add(Material.SMOOTH_RED_SANDSTONE);
//        items.add(Material.SMOOTH_SANDSTONE);
//        items.add(Material.SMOOTH_STONE);
//        items.add(Material.BRICKS);
//        items.add(Material.BOOKSHELF);
//        items.add(Material.MOSSY_COBBLESTONE);
//        items.add(Material.OBSIDIAN);
//        items.add(Material.PURPUR_BLOCK);
//        items.add(Material.PURPUR_PILLAR);
//        items.add(Material.PURPUR_STAIRS);
//        items.add(Material.OAK_STAIRS);
//        items.add(Material.DIAMOND_ORE); SILK
//        items.add(Material.DIAMOND_BLOCK);
//        items.add(Material.COBBLESTONE_STAIRS);
//        items.add(Material.REDSTONE_ORE);
//        items.add(Material.ICE);
//        items.add(Material.SNOW_BLOCK);
//        items.add(Material.CLAY);
//        items.add(Material.PUMPKIN);
//        items.add(Material.CARVED_PUMPKIN);
//        items.add(Material.NETHERRACK);
//        items.add(Material.SOUL_SAND);
//        items.add(Material.LIGHT_BLUE_TERRACOTTA);
//        items.add(Material.YELLOW_TERRACOTTA);
//        items.add(Material.LIME_TERRACOTTA);
//        items.add(Material.PINK_TERRACOTTA);
//        items.add(Material.GRAY_TERRACOTTA);
//        items.add(Material.LIGHT_GRAY_TERRACOTTA);
//        items.add(Material.CYAN_TERRACOTTA);
//        items.add(Material.PURPLE_TERRACOTTA);
//        items.add(Material.BLUE_TERRACOTTA);
//        items.add(Material.MELON);
//        items.add(Material.BRICK_STAIRS);
//        items.add(Material.STONE_BRICK_STAIRS);
//        items.add(Material.MYCELIUM); SILK
//        items.add(Material.NETHER_BRICKS);
//        items.add(Material.CRACKED_NETHER_BRICKS);
//        items.add(Material.CHISELED_NETHER_BRICKS);
//        items.add(Material.NETHER_BRICK_STAIRS);
//        items.add(Material.END_STONE);
//        items.add(Material.END_STONE_BRICKS);
//        items.add(Material.SANDSTONE_STAIRS);
//        items.add(Material.EMERALD_ORE); SILK
//        items.add(Material.EMERALD_BLOCK);
//        items.add(Material.SPRUCE_STAIRS);
//        items.add(Material.BIRCH_STAIRS);
//        items.add(Material.JUNGLE_STAIRS);
//        items.add(Material.CRIMSON_STAIRS);
//        items.add(Material.WARPED_STAIRS);
//        items.add(Material.NETHER_QUARTZ_ORE);
//        items.add(Material.CHISELED_QUARTZ_BLOCK);
//        items.add(Material.QUARTZ_BLOCK);
//        items.add(Material.QUARTZ_BRICKS);
//        items.add(Material.QUARTZ_PILLAR);
//        items.add(Material.QUARTZ_STAIRS);
//        items.add(Material.WHITE_TERRACOTTA);
//        items.add(Material.ORANGE_TERRACOTTA);
//        items.add(Material.MAGENTA_TERRACOTTA);
//        items.add(Material.PRISMARINE_BRICKS);
//        items.add(Material.DARK_PRISMARINE);
//        items.add(Material.PRISMARINE_STAIRS);
//        items.add(Material.PRISMARINE_BRICK_STAIRS);
//        items.add(Material.DARK_PRISMARINE_STAIRS);
//        items.add(Material.SEA_LANTERN); SILK
//        items.add(Material.RED_SANDSTONE);
//        items.add(Material.CHISELED_RED_SANDSTONE);
//        items.add(Material.CUT_RED_SANDSTONE);
//        items.add(Material.BROWN_TERRACOTTA);
//        items.add(Material.GREEN_TERRACOTTA);
//        items.add(Material.RED_TERRACOTTA);
//        items.add(Material.BLACK_TERRACOTTA);
//        items.add(Material.HAY_BLOCK);
//        items.add(Material.TERRACOTTA);
//        items.add(Material.COAL_BLOCK);
//        items.add(Material.PACKED_ICE); SILK
//        items.add(Material.ACACIA_STAIRS);
//        items.add(Material.DARK_OAK_STAIRS);
//        items.add(Material.WHITE_STAINED_GLASS);
//        items.add(Material.ORANGE_STAINED_GLASS);
//        items.add(Material.MAGENTA_STAINED_GLASS);
//        items.add(Material.LIGHT_BLUE_STAINED_GLASS);
//        items.add(Material.YELLOW_STAINED_GLASS);
//        items.add(Material.LIME_STAINED_GLASS);
//        items.add(Material.PINK_STAINED_GLASS);
//        items.add(Material.GRAY_STAINED_GLASS);
//        items.add(Material.LIGHT_GRAY_STAINED_GLASS);
//        items.add(Material.CYAN_STAINED_GLASS);
//        items.add(Material.PURPLE_STAINED_GLASS);
//        items.add(Material.BLUE_STAINED_GLASS);
//        items.add(Material.BROWN_STAINED_GLASS);
//        items.add(Material.GREEN_STAINED_GLASS);
//        items.add(Material.RED_STAINED_GLASS);
//        items.add(Material.BLACK_STAINED_GLASS);
//        items.add(Material.PRISMARINE);
//        items.add(Material.LIME_CONCRETE_POWDER);
//        items.add(Material.PINK_CONCRETE_POWDER);
//        items.add(Material.GRAY_CONCRETE_POWDER);
//        items.add(Material.LIGHT_GRAY_CONCRETE_POWDER);
//        items.add(Material.CYAN_CONCRETE_POWDER);
//        items.add(Material.PURPLE_CONCRETE_POWDER);
//        items.add(Material.BLUE_CONCRETE_POWDER);
//        items.add(Material.BROWN_CONCRETE_POWDER);
//        items.add(Material.GREEN_CONCRETE_POWDER);
//        items.add(Material.RED_SANDSTONE_STAIRS);
//        items.add(Material.MAGMA_BLOCK);
//        items.add(Material.NETHER_WART_BLOCK);
//        items.add(Material.WARPED_WART_BLOCK);
//        items.add(Material.RED_NETHER_BRICKS);
//        items.add(Material.BONE_BLOCK);
//        items.add(Material.WHITE_CONCRETE);
//        items.add(Material.ORANGE_CONCRETE);
//        items.add(Material.MAGENTA_CONCRETE);
//        items.add(Material.LIGHT_BLUE_CONCRETE);
//        items.add(Material.YELLOW_CONCRETE);
//        items.add(Material.LIME_CONCRETE);
//        items.add(Material.PINK_CONCRETE);
//        items.add(Material.GRAY_CONCRETE);
//        items.add(Material.LIGHT_GRAY_CONCRETE);
//        items.add(Material.CYAN_CONCRETE);
//        items.add(Material.PURPLE_CONCRETE);
//        items.add(Material.BLUE_CONCRETE);
//        items.add(Material.BROWN_CONCRETE);
//        items.add(Material.GREEN_CONCRETE);
//        items.add(Material.RED_CONCRETE);
//        items.add(Material.BLACK_CONCRETE);
//        items.add(Material.WHITE_CONCRETE_POWDER);
//        items.add(Material.ORANGE_CONCRETE_POWDER);
//        items.add(Material.MAGENTA_CONCRETE_POWDER);
//        items.add(Material.LIGHT_BLUE_CONCRETE_POWDER);
//        items.add(Material.YELLOW_CONCRETE_POWDER);
//        items.add(Material.POLISHED_GRANITE_SLAB);
//        items.add(Material.SMOOTH_RED_SANDSTONE_SLAB);
//        items.add(Material.MOSSY_STONE_BRICK_SLAB);
//        items.add(Material.POLISHED_DIORITE_SLAB);
//        items.add(Material.MOSSY_COBBLESTONE_SLAB);
//        items.add(Material.END_STONE_BRICK_SLAB);
//        items.add(Material.SMOOTH_SANDSTONE_SLAB);
//        items.add(Material.SMOOTH_QUARTZ_SLAB);
//        items.add(Material.GRANITE_SLAB);
//        items.add(Material.RED_CONCRETE_POWDER);
//        items.add(Material.BLACK_CONCRETE_POWDER);
//        items.add(Material.DEAD_TUBE_CORAL_BLOCK); //NEDÁVAT OD SPODU
//        items.add(Material.DEAD_BRAIN_CORAL_BLOCK);
//        items.add(Material.DEAD_BUBBLE_CORAL_BLOCK);
//        items.add(Material.DEAD_FIRE_CORAL_BLOCK);
//        items.add(Material.DEAD_HORN_CORAL_BLOCK);
//        items.add(Material.TUBE_CORAL_BLOCK);
//        items.add(Material.BRAIN_CORAL_BLOCK);
//        items.add(Material.BUBBLE_CORAL_BLOCK);
//        items.add(Material.FIRE_CORAL_BLOCK);
//        items.add(Material.HORN_CORAL_BLOCK);
//        items.add(Material.BLUE_ICE); //NEDÁVAT OD HORA
//        items.add(Material.POLISHED_GRANITE_STAIRS);
//        items.add(Material.SMOOTH_RED_SANDSTONE_STAIRS);
//        items.add(Material.MOSSY_STONE_BRICK_STAIRS);
//        items.add(Material.POLISHED_DIORITE_STAIRS);
//        items.add(Material.MOSSY_COBBLESTONE_STAIRS);
//        items.add(Material.END_STONE_BRICK_STAIRS);
//        items.add(Material.STONE_STAIRS);
//        items.add(Material.SMOOTH_SANDSTONE_STAIRS);
//        items.add(Material.SMOOTH_QUARTZ_STAIRS);
//        items.add(Material.GRANITE_STAIRS);
//        items.add(Material.ANDESITE_STAIRS);
//        items.add(Material.RED_NETHER_BRICK_STAIRS);
//        items.add(Material.POLISHED_ANDESITE_STAIRS);
//        items.add(Material.DIORITE_STAIRS);
//        items.add(Material.ANDESITE_SLAB);
//        items.add(Material.RED_NETHER_BRICK_SLAB);
//        items.add(Material.POLISHED_ANDESITE_SLAB);
//        items.add(Material.DIORITE_SLAB);
//        items.add(Material.DRIED_KELP_BLOCK);
//        items.add(Material.NETHERITE_BLOCK);
//        items.add(Material.ANCIENT_DEBRIS);
//        items.add(Material.CRYING_OBSIDIAN);
//        items.add(Material.BLACKSTONE);
//        items.add(Material.BLACKSTONE_SLAB);
//        items.add(Material.BLACKSTONE_STAIRS);
//        items.add(Material.GILDED_BLACKSTONE);
//        items.add(Material.POLISHED_BLACKSTONE);
//        items.add(Material.POLISHED_BLACKSTONE_SLAB);
//        items.add(Material.POLISHED_BLACKSTONE_STAIRS);
//        items.add(Material.CHISELED_POLISHED_BLACKSTONE);
//        items.add(Material.POLISHED_BLACKSTONE_BRICKS);
//        items.add(Material.POLISHED_BLACKSTONE_BRICK_SLAB);
//        items.add(Material.POLISHED_BLACKSTONE_BRICK_STAIRS);
//        items.add(Material.CRACKED_POLISHED_BLACKSTONE_BRICKS);
        //endregion

        //region Decoration Blocks
//        items.add(Material.OXEYE_DAISY);
//        items.add(Material.CORNFLOWER);
//        items.add(Material.LILY_OF_THE_VALLEY);
//        items.add(Material.WITHER_ROSE);
//        items.add(Material.BROWN_MUSHROOM);
//        items.add(Material.RED_MUSHROOM);
//        items.add(Material.CRIMSON_FUNGUS);
//        items.add(Material.WARPED_FUNGUS);
//        items.add(Material.CRIMSON_ROOTS); SILK
//        items.add(Material.OAK_SAPLING);
//        items.add(Material.SPRUCE_SAPLING);
//        items.add(Material.BIRCH_SAPLING);
//        items.add(Material.JUNGLE_SAPLING);
//        items.add(Material.ACACIA_SAPLING);
//        items.add(Material.DARK_OAK_SAPLING);
//        items.add(Material.OAK_LEAVES);
//        items.add(Material.SPRUCE_LEAVES);
//        items.add(Material.BIRCH_LEAVES);
//        items.add(Material.JUNGLE_LEAVES);
//        items.add(Material.ACACIA_LEAVES);
//        items.add(Material.DARK_OAK_LEAVES);
//        items.add(Material.COBWEB);
//        items.add(Material.GRASS);
//        items.add(Material.FERN);
//        items.add(Material.DEAD_BUSH);
//        items.add(Material.SEAGRASS);
//        items.add(Material.SEA_PICKLE);
//        items.add(Material.DANDELION);
//        items.add(Material.POPPY);
//        items.add(Material.BLUE_ORCHID);
//        items.add(Material.ALLIUM);
//        items.add(Material.AZURE_BLUET);
//        items.add(Material.RED_TULIP);
//        items.add(Material.ORANGE_TULIP);
//        items.add(Material.WHITE_TULIP);
//        items.add(Material.PINK_TULIP);
//        items.add(Material.POLISHED_BLACKSTONE_BRICK_WALL);
//        items.add(Material.ANVIL);
//        items.add(Material.WHITE_CARPET);
//        items.add(Material.ORANGE_CARPET);
//        items.add(Material.MAGENTA_CARPET);
//        items.add(Material.LIGHT_BLUE_CARPET);
//        items.add(Material.YELLOW_CARPET);
//        items.add(Material.LIME_CARPET);
//        items.add(Material.PINK_CARPET);
//        items.add(Material.SOUL_TORCH);
//        items.add(Material.IRON_BARS);
//        items.add(Material.CHAIN);
//        items.add(Material.GLASS_PANE);
//        items.add(Material.VINE);
//        items.add(Material.NETHER_BRICK_FENCE);
//        items.add(Material.ENCHANTING_TABLE);
//        items.add(Material.ENDER_CHEST);
//        items.add(Material.COBBLESTONE_WALL);
//        items.add(Material.MOSSY_COBBLESTONE_WALL);
//        items.add(Material.BRICK_WALL);
//        items.add(Material.RED_SANDSTONE_WALL);
//        items.add(Material.MOSSY_STONE_BRICK_WALL);
//        items.add(Material.GRANITE_WALL);
//        items.add(Material.PRISMARINE_WALL);
//        items.add(Material.STONE_BRICK_WALL);
//        items.add(Material.NETHER_BRICK_WALL);
//        items.add(Material.ANDESITE_WALL);
//        items.add(Material.RED_NETHER_BRICK_WALL);
//        items.add(Material.SANDSTONE_WALL);
//        items.add(Material.END_STONE_BRICK_WALL);
//        items.add(Material.DIORITE_WALL);
//        items.add(Material.BLACKSTONE_WALL);
//        items.add(Material.POLISHED_BLACKSTONE_WALL);
//        items.add(Material.GREEN_STAINED_GLASS_PANE);
//        items.add(Material.RED_STAINED_GLASS_PANE);
//        items.add(Material.BLACK_STAINED_GLASS_PANE);
//        items.add(Material.SHULKER_BOX);
//        items.add(Material.WHITE_SHULKER_BOX);
//        items.add(Material.ORANGE_SHULKER_BOX);
//        items.add(Material.MAGENTA_SHULKER_BOX);
//        items.add(Material.LIGHT_BLUE_SHULKER_BOX);
//        items.add(Material.YELLOW_SHULKER_BOX);
//        items.add(Material.GRAY_CARPET);
//        items.add(Material.LIGHT_GRAY_CARPET);
//        items.add(Material.CYAN_CARPET);
//        items.add(Material.PURPLE_CARPET);
//        items.add(Material.BROWN_CARPET);
//        items.add(Material.GREEN_CARPET);
//        items.add(Material.RED_CARPET);
//        items.add(Material.BLACK_CARPET);
//        items.add(Material.BLUE_CARPET);
//        items.add(Material.SLIME_BLOCK);
//        items.add(Material.SUNFLOWER);
//        items.add(Material.LILAC);
//        items.add(Material.PEONY);
//        items.add(Material.WHITE_STAINED_GLASS_PANE);
//        items.add(Material.ROSE_BUSH);
//        items.add(Material.MAGENTA_STAINED_GLASS_PANE);
//        items.add(Material.LIGHT_BLUE_STAINED_GLASS_PANE);
//        items.add(Material.ORANGE_STAINED_GLASS_PANE);
//        items.add(Material.YELLOW_STAINED_GLASS_PANE);
//        items.add(Material.LIME_STAINED_GLASS_PANE);
//        items.add(Material.PINK_STAINED_GLASS_PANE);
//        items.add(Material.GRAY_STAINED_GLASS_PANE);
//        items.add(Material.LIGHT_GRAY_STAINED_GLASS_PANE);
//        items.add(Material.CYAN_STAINED_GLASS_PANE);
//        items.add(Material.PURPLE_STAINED_GLASS_PANE);
//        items.add(Material.BLUE_STAINED_GLASS_PANE);
//        items.add(Material.BROWN_STAINED_GLASS_PANE);
//        items.add(Material.TUBE_CORAL); //nedávat od spodu
//        items.add(Material.BRAIN_CORAL);
//        items.add(Material.BUBBLE_CORAL);
//        items.add(Material.FIRE_CORAL);
//        items.add(Material.HORN_CORAL);
//        items.add(Material.DEAD_BRAIN_CORAL);
//        items.add(Material.DEAD_BUBBLE_CORAL);
//        items.add(Material.DEAD_FIRE_CORAL);
//        items.add(Material.DEAD_HORN_CORAL); //nedávat od hora
//        items.add(Material.LIME_SHULKER_BOX);
//        items.add(Material.PINK_SHULKER_BOX);
//        items.add(Material.GRAY_SHULKER_BOX);
//        items.add(Material.CYAN_SHULKER_BOX);
//        items.add(Material.PURPLE_SHULKER_BOX);
//        items.add(Material.BLUE_SHULKER_BOX);
//        items.add(Material.BROWN_SHULKER_BOX);
//        items.add(Material.GREEN_SHULKER_BOX);
//        items.add(Material.LIGHT_GRAY_SHULKER_BOX);
//        items.add(Material.RED_SHULKER_BOX);
//        items.add(Material.BLACK_SHULKER_BOX);
//        items.add(Material.WHITE_GLAZED_TERRACOTTA);
//        items.add(Material.MAGENTA_GLAZED_TERRACOTTA);
//        items.add(Material.LIGHT_BLUE_GLAZED_TERRACOTTA);
//        items.add(Material.ORANGE_GLAZED_TERRACOTTA);
//        items.add(Material.LIME_GLAZED_TERRACOTTA);
//        items.add(Material.YELLOW_GLAZED_TERRACOTTA);
//        items.add(Material.PINK_GLAZED_TERRACOTTA);
//        items.add(Material.GRAY_GLAZED_TERRACOTTA);
//        items.add(Material.LIGHT_GRAY_GLAZED_TERRACOTTA);
//        items.add(Material.CYAN_GLAZED_TERRACOTTA);
//        items.add(Material.BLUE_GLAZED_TERRACOTTA);
//        items.add(Material.GREEN_GLAZED_TERRACOTTA);
//        items.add(Material.BROWN_GLAZED_TERRACOTTA);
//        items.add(Material.PURPLE_GLAZED_TERRACOTTA);
//        items.add(Material.RED_GLAZED_TERRACOTTA);
//        items.add(Material.BLACK_GLAZED_TERRACOTTA);
//        items.add(Material.PINK_BED);
//        items.add(Material.GRAY_BED);
//        items.add(Material.LIGHT_GRAY_BED);
//        items.add(Material.CYAN_BED);
//        items.add(Material.PURPLE_BED);
//        items.add(Material.BLUE_BED);
//        items.add(Material.BROWN_BED);
//        items.add(Material.GREEN_BED);
//        items.add(Material.RED_BED);
//        items.add(Material.DEAD_TUBE_CORAL); //nedávat od spodu
//        items.add(Material.TUBE_CORAL_FAN);
//        items.add(Material.BRAIN_CORAL_FAN);
//        items.add(Material.BUBBLE_CORAL_FAN);
//        items.add(Material.FIRE_CORAL_FAN);
//        items.add(Material.HORN_CORAL_FAN);
//        items.add(Material.DEAD_TUBE_CORAL_FAN);
//        items.add(Material.DEAD_BRAIN_CORAL_FAN);
//        items.add(Material.DEAD_BUBBLE_CORAL_FAN);
//        items.add(Material.DEAD_FIRE_CORAL_FAN);
//        items.add(Material.DEAD_HORN_CORAL_FAN); //nedávat od hora
//        items.add(Material.SCAFFOLDING);
//        items.add(Material.PAINTING);
//        items.add(Material.OAK_SIGN);
//        items.add(Material.SPRUCE_SIGN);
//        items.add(Material.BIRCH_SIGN);
//        items.add(Material.JUNGLE_SIGN);
//        items.add(Material.ACACIA_SIGN);
//        items.add(Material.DARK_OAK_SIGN);
//        items.add(Material.CRIMSON_SIGN);
//        items.add(Material.WARPED_SIGN);
//        items.add(Material.WHITE_BED);
//        items.add(Material.ORANGE_BED);
//        items.add(Material.MAGENTA_BED);
//        items.add(Material.LIGHT_BLUE_BED);
//        items.add(Material.YELLOW_BED);
//        items.add(Material.LIME_BED);
//        items.add(Material.SMOKER);
//        items.add(Material.BLAST_FURNACE);
//        items.add(Material.CARTOGRAPHY_TABLE);
//        items.add(Material.FLETCHING_TABLE);
//        items.add(Material.GRINDSTONE);
//        items.add(Material.SMITHING_TABLE);
//        items.add(Material.STONECUTTER);
//        items.add(Material.BELL);
//        items.add(Material.LANTERN);
//        items.add(Material.BLACK_BED);
//        items.add(Material.FLOWER_POT);
//        items.add(Material.WITHER_SKELETON_SKULL);
//        items.add(Material.DRAGON_HEAD);
//        items.add(Material.ARMOR_STAND);
//        items.add(Material.WHITE_BANNER);
//        items.add(Material.ITEM_FRAME);
//        items.add(Material.ORANGE_BANNER);
//        items.add(Material.MAGENTA_BANNER);
//        items.add(Material.LIGHT_BLUE_BANNER);
//        items.add(Material.YELLOW_BANNER);
//        items.add(Material.LIME_BANNER);
//        items.add(Material.PINK_BANNER);
//        items.add(Material.GRAY_BANNER);
//        items.add(Material.LIGHT_GRAY_BANNER);
//        items.add(Material.CYAN_BANNER);
//        items.add(Material.PURPLE_BANNER);
//        items.add(Material.BLUE_BANNER);
//        items.add(Material.BROWN_BANNER);
//        items.add(Material.GREEN_BANNER);
//        items.add(Material.RED_BANNER);
//        items.add(Material.BLACK_BANNER);
//        items.add(Material.END_CRYSTAL);
//        items.add(Material.LOOM);
//        items.add(Material.COMPOSTER);
//        items.add(Material.BARREL);
//        items.add(Material.SOUL_LANTERN);
//        items.add(Material.SOUL_CAMPFIRE);
//        items.add(Material.SHROOMLIGHT);
//        items.add(Material.HONEY_BLOCK);
//        items.add(Material.LODESTONE);
//        items.add(Material.HONEYCOMB_BLOCK);
//        items.add(Material.BEEHIVE);
//        items.add(Material.BEE_NEST); SILK
//        items.add(Material.CAMPFIRE);
//        items.add(Material.RESPAWN_ANCHOR);
        //endregion

        //region Redstone & Transport
//        items.add(Material.BIRCH_FENCE_GATE);
//        items.add(Material.JUNGLE_FENCE_GATE);
//        items.add(Material.ACACIA_FENCE_GATE);
//        items.add(Material.DARK_OAK_FENCE_GATE);
//        items.add(Material.CRIMSON_FENCE_GATE);
//        items.add(Material.WARPED_FENCE_GATE);
//        items.add(Material.REDSTONE_LAMP);
//        items.add(Material.TRIPWIRE_HOOK);
//        items.add(Material.STONE_BUTTON);
//        items.add(Material.DISPENSER);
//        items.add(Material.NOTE_BLOCK);
//        items.add(Material.STICKY_PISTON);
//        items.add(Material.PISTON);
//        items.add(Material.TNT);
//        items.add(Material.LEVER);
//        items.add(Material.STONE_PRESSURE_PLATE);
//        items.add(Material.OAK_PRESSURE_PLATE);
//        items.add(Material.SPRUCE_PRESSURE_PLATE);
//        items.add(Material.BIRCH_PRESSURE_PLATE);
//        items.add(Material.JUNGLE_PRESSURE_PLATE);
//        items.add(Material.ACACIA_PRESSURE_PLATE);
//        items.add(Material.DARK_OAK_PRESSURE_PLATE);
//        items.add(Material.CRIMSON_PRESSURE_PLATE);
//        items.add(Material.WARPED_PRESSURE_PLATE);
//        items.add(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE);
//        items.add(Material.REDSTONE_TORCH);
//        items.add(Material.OAK_TRAPDOOR);
//        items.add(Material.SPRUCE_TRAPDOOR);
//        items.add(Material.BIRCH_TRAPDOOR);
//        items.add(Material.JUNGLE_TRAPDOOR);
//        items.add(Material.ACACIA_TRAPDOOR);
//        items.add(Material.CRIMSON_TRAPDOOR);
//        items.add(Material.WARPED_TRAPDOOR);
//        items.add(Material.DARK_OAK_TRAPDOOR);
//        items.add(Material.OAK_FENCE_GATE);
//        items.add(Material.SPRUCE_FENCE_GATE);
//        items.add(Material.REPEATER);
//        items.add(Material.COMPARATOR);
//        items.add(Material.REDSTONE);
//        items.add(Material.LECTERN);
//        items.add(Material.TARGET);
//        items.add(Material.OAK_BUTTON);
//        items.add(Material.SPRUCE_BUTTON);
//        items.add(Material.BIRCH_BUTTON);
//        items.add(Material.JUNGLE_BUTTON);
//        items.add(Material.ACACIA_BUTTON);
//        items.add(Material.DARK_OAK_BUTTON);
//        items.add(Material.CRIMSON_BUTTON);
//        items.add(Material.WARPED_BUTTON);
//        items.add(Material.POLISHED_BLACKSTONE_BUTTON);
//        items.add(Material.TRAPPED_CHEST);
//        items.add(Material.LIGHT_WEIGHTED_PRESSURE_PLATE);
//        items.add(Material.HEAVY_WEIGHTED_PRESSURE_PLATE);
//        items.add(Material.DAYLIGHT_DETECTOR);
//        items.add(Material.REDSTONE_BLOCK);
//        items.add(Material.HOPPER);
//        items.add(Material.DROPPER);
//        items.add(Material.OBSERVER);
//        items.add(Material.IRON_TRAPDOOR);
//        items.add(Material.IRON_DOOR);
//        items.add(Material.OAK_DOOR);
//        items.add(Material.SPRUCE_DOOR);
//        items.add(Material.BIRCH_DOOR);
//        items.add(Material.JUNGLE_DOOR);
//        items.add(Material.ACACIA_DOOR);
//        items.add(Material.CRIMSON_DOOR);
//        items.add(Material.WARPED_DOOR);
//        items.add(Material.DARK_OAK_DOOR);
//        items.add(Material.POWERED_RAIL);
//        items.add(Material.DETECTOR_RAIL);
//        items.add(Material.RAIL);
//        items.add(Material.ACTIVATOR_RAIL);
//        items.add(Material.MINECART);
//        items.add(Material.SADDLE); //idk asi bych to nikam nedal
//        items.add(Material.OAK_BOAT);
//        items.add(Material.CHEST_MINECART);
//        items.add(Material.FURNACE_MINECART);
//        items.add(Material.CARROT_ON_A_STICK);
//        items.add(Material.WARPED_FUNGUS_ON_A_STICK);
//        items.add(Material.HOPPER_MINECART);
//        items.add(Material.TNT_MINECART);
//        items.add(Material.SPRUCE_BOAT);
//        items.add(Material.BIRCH_BOAT);
//        items.add(Material.JUNGLE_BOAT);
//        items.add(Material.ACACIA_BOAT);
//        items.add(Material.ELYTRA);
//        items.add(Material.DARK_OAK_BOAT);
        //endregion

        //region Miscellaneous
//        items.add(Material.COD_BUCKET);
//        items.add(Material.TROPICAL_FISH_BUCKET);
//        items.add(Material.BRICK);
//        items.add(Material.CLAY_BALL);
//        items.add(Material.PAPER);
//        items.add(Material.BOOK);
//        items.add(Material.SLIME_BALL);
//        items.add(Material.EGG);
//        items.add(Material.GLOWSTONE_DUST);
//        items.add(Material.BEACON);
//        items.add(Material.TURTLE_EGG); SILK
//        items.add(Material.CONDUIT);
//        items.add(Material.SCUTE);
//        items.add(Material.COAL);
//        items.add(Material.CHARCOAL);
//        items.add(Material.DIAMOND);
//        items.add(Material.IRON_INGOT);
//        items.add(Material.GOLD_INGOT);
//        items.add(Material.NETHERITE_INGOT);
//        items.add(Material.NETHERITE_SCRAP);
//        items.add(Material.STICK);
//        items.add(Material.BOWL);
//        items.add(Material.STRING);
//        items.add(Material.FEATHER);
//        items.add(Material.GUNPOWDER);
//        items.add(Material.WHEAT_SEEDS);
//        items.add(Material.WHEAT);
//        items.add(Material.BUCKET);
//        items.add(Material.FLINT);
//        items.add(Material.WATER_BUCKET);
//        items.add(Material.LAVA_BUCKET);
//        items.add(Material.SNOWBALL);
//        items.add(Material.LEATHER);
//        items.add(Material.MILK_BUCKET);
//        items.add(Material.PUFFERFISH_BUCKET);
//        items.add(Material.SALMON_BUCKET);
//        items.add(Material.NETHER_WART);
//        items.add(Material.ENDER_EYE);
//        items.add(Material.FIRE_CHARGE);
//        items.add(Material.WRITABLE_BOOK);
//        items.add(Material.EMERALD);
//        items.add(Material.MAP);
//        items.add(Material.NETHER_STAR);
//        items.add(Material.FIREWORK_ROCKET);
//        items.add(Material.INK_SAC);
//        items.add(Material.COCOA_BEANS);
//        items.add(Material.LAPIS_LAZULI);
//        items.add(Material.WHITE_DYE);
//        items.add(Material.ORANGE_DYE);
//        items.add(Material.MAGENTA_DYE);
//        items.add(Material.LIGHT_BLUE_DYE);
//        items.add(Material.YELLOW_DYE);
//        items.add(Material.LIME_DYE);
//        items.add(Material.PINK_DYE);
//        items.add(Material.GRAY_DYE);
//        items.add(Material.LIGHT_GRAY_DYE);
//        items.add(Material.CYAN_DYE);
//        items.add(Material.PURPLE_DYE);
//        items.add(Material.BLUE_DYE);
//        items.add(Material.BROWN_DYE);
//        items.add(Material.GREEN_DYE);
//        items.add(Material.RED_DYE);
//        items.add(Material.BLACK_DYE);
//        items.add(Material.BONE_MEAL);
//        items.add(Material.BONE);
//        items.add(Material.SUGAR);
//        items.add(Material.PUMPKIN_SEEDS);
//        items.add(Material.MELON_SEEDS);
//        items.add(Material.ENDER_PEARL);
//        items.add(Material.BLAZE_ROD);
//        items.add(Material.GOLD_NUGGET);
//        items.add(Material.HONEYCOMB);
//        items.add(Material.FIREWORK_STAR);
//        items.add(Material.NETHER_BRICK);
//        items.add(Material.PRISMARINE_SHARD);
//        items.add(Material.QUARTZ);
//        items.add(Material.PRISMARINE_CRYSTALS);
//        items.add(Material.RABBIT_HIDE);
//        items.add(Material.CHORUS_FRUIT);
//        items.add(Material.POPPED_CHORUS_FRUIT);
//        items.add(Material.BEETROOT_SEEDS);
//        items.add(Material.SHULKER_SHELL);
//        items.add(Material.HONEYCOMB);
//        items.add(Material.HEART_OF_THE_SEA);
//        items.add(Material.IRON_NUGGET);
//        items.add(Material.NAUTILUS_SHELL);
        //endregion

        //region Foodstuffs
//        items.add(Material.PUMPKIN_PIE);
//        items.add(Material.RABBIT);
//        items.add(Material.COOKED_RABBIT);
//        items.add(Material.RABBIT_STEW);
//        items.add(Material.MUTTON);
//        items.add(Material.COOKED_MUTTON);
//        items.add(Material.BEETROOT);
//        items.add(Material.BEETROOT_SOUP);
//        items.add(Material.SWEET_BERRIES);
//        items.add(Material.APPLE);
//        items.add(Material.MUSHROOM_STEW);
//        items.add(Material.BREAD);
//        items.add(Material.PORKCHOP);
//        items.add(Material.GOLDEN_APPLE);
//        items.add(Material.COOKED_PORKCHOP);
//        items.add(Material.ENCHANTED_GOLDEN_APPLE);
//        items.add(Material.COD);
//        items.add(Material.SALMON);
//        items.add(Material.TROPICAL_FISH);
//        items.add(Material.PUFFERFISH);
//        items.add(Material.COOKED_COD);
//        items.add(Material.COOKED_SALMON);
//        items.add(Material.CAKE);
//        items.add(Material.COOKIE);
//        items.add(Material.MELON_SLICE);
//        items.add(Material.DRIED_KELP);
//        items.add(Material.BEEF);
//        items.add(Material.COOKED_BEEF);
//        items.add(Material.CHICKEN);
//        items.add(Material.COOKED_CHICKEN);
//        items.add(Material.ROTTEN_FLESH);
//        items.add(Material.SPIDER_EYE);
//        items.add(Material.CARROT);
//        items.add(Material.POTATO);
//        items.add(Material.BAKED_POTATO);
//        items.add(Material.POISONOUS_POTATO);
//        items.add(Material.HONEY_BOTTLE);
        //endregion

        //region Tools
//        items.add(Material.CLOCK);
//        items.add(Material.SHEARS);
//        items.add(Material.LEAD);
//        items.add(Material.NAME_TAG); //asi bych to nedával nebo do hodně pozdní fáze
//        items.add(Material.FLINT_AND_STEEL);
//        items.add(Material.WOODEN_SHOVEL);
//        items.add(Material.WOODEN_PICKAXE);
//        items.add(Material.WOODEN_AXE);
//        items.add(Material.WOODEN_HOE);
//        items.add(Material.STONE_SHOVEL);
//        items.add(Material.STONE_PICKAXE);
//        items.add(Material.STONE_AXE);
//        items.add(Material.STONE_HOE);
//        items.add(Material.GOLDEN_SHOVEL);
//        items.add(Material.GOLDEN_PICKAXE);
//        items.add(Material.GOLDEN_AXE);
//        items.add(Material.GOLDEN_HOE);
//        items.add(Material.IRON_SHOVEL);
//        items.add(Material.IRON_PICKAXE);
//        items.add(Material.IRON_AXE);
//        items.add(Material.IRON_HOE);
//        items.add(Material.DIAMOND_SHOVEL);
//        items.add(Material.DIAMOND_PICKAXE);
//        items.add(Material.DIAMOND_AXE);
//        items.add(Material.DIAMOND_HOE);
//        items.add(Material.NETHERITE_SHOVEL);
//        items.add(Material.NETHERITE_PICKAXE);
//        items.add(Material.NETHERITE_AXE);
//        items.add(Material.NETHERITE_HOE);
//        items.add(Material.COMPASS);
//        items.add(Material.FISHING_ROD);
        //endregion

        //region Combat
//        items.add(Material.GOLDEN_LEGGINGS);
//        items.add(Material.GOLDEN_BOOTS);
//        items.add(Material.NETHERITE_HELMET);
//        items.add(Material.NETHERITE_CHESTPLATE);
//        items.add(Material.NETHERITE_LEGGINGS);
//        items.add(Material.NETHERITE_BOOTS);
//        items.add(Material.SPECTRAL_ARROW);
//        items.add(Material.SHIELD);
//        items.add(Material.TOTEM_OF_UNDYING);
//        items.add(Material.BOW);
//        items.add(Material.ARROW);
//        items.add(Material.WOODEN_SWORD);
//        items.add(Material.STONE_SWORD);
//        items.add(Material.GOLDEN_SWORD);
//        items.add(Material.IRON_SWORD);
//        items.add(Material.DIAMOND_SWORD);
//        items.add(Material.NETHERITE_SWORD);
//        items.add(Material.TURTLE_HELMET);
//        items.add(Material.CHAINMAIL_HELMET);
//        items.add(Material.CHAINMAIL_CHESTPLATE);
//        items.add(Material.CHAINMAIL_LEGGINGS);
//        items.add(Material.CHAINMAIL_BOOTS);
//        items.add(Material.IRON_HELMET);
//        items.add(Material.LEATHER_HELMET);
//        items.add(Material.LEATHER_CHESTPLATE);
//        items.add(Material.LEATHER_LEGGINGS);
//        items.add(Material.LEATHER_BOOTS);
//        items.add(Material.DIAMOND_CHESTPLATE);
//        items.add(Material.DIAMOND_LEGGINGS);
//        items.add(Material.DIAMOND_BOOTS);
//        items.add(Material.GOLDEN_HELMET);
//        items.add(Material.GOLDEN_CHESTPLATE);
//        items.add(Material.IRON_BOOTS);
//        items.add(Material.IRON_LEGGINGS);
//        items.add(Material.DIAMOND_HELMET);
//        items.add(Material.IRON_CHESTPLATE);
//        items.add(Material.TRIDENT);
//        items.add(Material.CROSSBOW);
        //endregion

        //region Brewing
//        items.add(Material.PHANTOM_MEMBRANE);
//        items.add(Material.GHAST_TEAR);
//        items.add(Material.GLASS_BOTTLE);
//        items.add(Material.FERMENTED_SPIDER_EYE);
//        items.add(Material.BLAZE_POWDER);
//        items.add(Material.MAGMA_CREAM);
//        items.add(Material.BREWING_STAND);
//        items.add(Material.CAULDRON);
//        items.add(Material.GLISTERING_MELON_SLICE);
//        items.add(Material.GOLDEN_CARROT);
//        items.add(Material.DRAGON_BREATH);
//        items.add(Material.RABBIT_FOOT);
        //endregion

        //region 1.17
        //items.add(Material.SMALL_AMETHYST_BUD);
        //items.add(Material.MEDIUM_AMETHYST_BUD);
        //items.add(Material.LARGE_AMETHYST_BUD);
        //items.add(Material.AMETHYST_CLUSTER);
        //items.add(Material.AZALEA);
        //items.add(Material.FLOWERING_AZALEA);
        //items.add(Material.AZALEA_LEAVES);
        //items.add(Material.FLOWERING_AZALEA_LEAVES);
        //items.add(Material.AMETHYST_BLOCK);
        //items.add(Material.COPPER_BLOCK);
        //items.add(Material.RAW_COPPER_BLOCK);
        //items.add(Material.RAW_IRON_BLOCK);
        //items.add(Material.RAW_GOLD_BLOCK);
        //items.add(Material.CALCITE);
        //items.add(Material.CANDLE);
        //items.add(Material.WHITE_CANDLE);
        //items.add(Material.ORANGE_CANDLE);
        //items.add(Material.MAGENTA_CANDLE);
        //items.add(Material.LIGHT_BLUE_CANDLE);
        //items.add(Material.YELLOW_CANDLE);
        //items.add(Material.LIME_CANDLE);
        //items.add(Material.PINK_CANDLE);
        //items.add(Material.GRAY_CANDLE);
        //items.add(Material.LIGHT_GRAY_CANDLE);
        //items.add(Material.CYAN_CANDLE);
        //items.add(Material.PURPLE_CANDLE);
        //items.add(Material.BLUE_CANDLE);
        //items.add(Material.BROWN_CANDLE);
        //items.add(Material.GREEN_CANDLE);
        //items.add(Material.RED_CANDLE);
        //items.add(Material.BLACK_CANDLE);
        //items.add(Material.COBBLED_DEEPSLATE);
        //items.add(Material.COPPER_ORE);
        //items.add(Material.CUT_COPPER);
        //items.add(Material.CUT_COPPER_SLAB);
        //items.add(Material.CUT_COPPER_STAIRS);
        //items.add(Material.EXPOSED_COPPER);
        //items.add(Material.WEATHERED_COPPER);
        //items.add(Material.OXIDIZED_COPPER);
        //items.add(Material.EXPOSED_CUT_COPPER);
        //items.add(Material.WEATHERED_CUT_COPPER);
        //items.add(Material.OXIDIZED_CUT_COPPER);
        //items.add(Material.WEATHERED_CUT_COPPER_STAIRS);
        //items.add(Material.OXIDIZED_CUT_COPPER_STAIRS);
        //items.add(Material.EXPOSED_CUT_COPPER_SLAB);
        //items.add(Material.WEATHERED_CUT_COPPER_SLAB);
        //items.add(Material.OXIDIZED_CUT_COPPER_SLAB);
        //items.add(Material.WAXED_COPPER_BLOCK);
        //items.add(Material.WAXED_EXPOSED_CUT_COPPER);
        //items.add(Material.WAXED_WEATHERED_COPPER);
        //items.add(Material.WAXED_OXIDIZED_COPPER);
        //items.add(Material.WAXED_CUT_COPPER);
        //items.add(Material.WAXED_EXPOSED_CUT_COPPER);
        //items.add(Material.WAXED_WEATHERED_CUT_COPPER);
        //items.add(Material.WAXED_OXIDIZED_CUT_COPPER);
        //items.add(Material.WAXED_CUT_COPPER_STAIRS);
        //items.add(Material.WAXED_EXPOSED_CUT_COPPER_STAIRS);
        //items.add(Material.WAXED_WEATHERED_CUT_COPPER_STAIRS);
        //items.add(Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS);
        //items.add(Material.WAXED_CUT_COPPER_SLAB);
        //items.add(Material.WAXED_EXPOSED_CUT_COPPER_SLAB);
        //items.add(Material.WAXED_WEATHERED_CUT_COPPER_SLAB);
        //items.add(Material.WAXED_OXIDIZED_CUT_COPPER_SLAB);
        //items.add(Material.DEEPSLATE);
        //items.add(Material.COBBLED_DEEPSLATE_SLAB);
        //items.add(Material.COBBLED_DEEPSLATE_STAIRS);
        //items.add(Material.COBBLED_DEEPSLATE_WALL);
        //items.add(Material.POLISHED_DEEPSLATE);
        //items.add(Material.POLISHED_DEEPSLATE_SLAB);
        //items.add(Material.POLISHED_DEEPSLATE_STAIRS);
        //items.add(Material.POLISHED_DEEPSLATE_WALL);
        //items.add(Material.DEEPSLATE_BRICKS);
        //items.add(Material.CRACKED_DEEPSLATE_BRICKS);
        //items.add(Material.DEEPSLATE_BRICK_SLAB);
        //items.add(Material.DEEPSLATE_BRICK_STAIRS);
        //items.add(Material.DEEPSLATE_BRICK_WALL);
        //items.add(Material.DEEPSLATE_TILES);
        //items.add(Material.CRACKED_DEEPSLATE_TILES);
        //items.add(Material.DEEPSLATE_TILE_SLAB);
        //items.add(Material.DEEPSLATE_TILE_STAIRS);
        //items.add(Material.DEEPSLATE_TILE_WALL);
        //items.add(Material.CHISELED_DEEPSLATE);
        //items.add(Material.DEEPSLATE_IRON_ORE);
        //items.add(Material.DEEPSLATE_COPPER_ORE);
        //items.add(Material.DEEPSLATE_GOLD_ORE);
        //items.add(Material.DEEPSLATE_DIAMOND_ORE);
        //items.add(Material.DEEPSLATE_REDSTONE_ORE);
        //items.add(Material.DEEPSLATE_EMERALD_ORE);
        //items.add(Material.DEEPSLATE_LAPIS_ORE);
        //items.add(Material.GLOW_ITEM_FRAME);
        //items.add(Material.GLOW_LICHEN);
        //items.add(Material.HANGING_ROOTS);
        //items.add(Material.LIGHTNING_ROD);
        //items.add(Material.MOSS_BLOCK);
        //items.add(Material.MOSS_CARPET);
        //items.add(Material.POINTED_DRIPSTONE);
        //items.add(Material.POWDER_SNOW_BUCKET);
        //items.add(Material.ROOTED_DIRT);
        //items.add(Material.SMOOTH_BASALT);
        //items.add(Material.SPORE_BLOSSOM);
        //items.add(Material.TINTED_GLASS);
        //items.add(Material.AMETHYST_SHARD);
        //items.add(Material.AXOLOTL_BUCKET);
        //items.add(Material.COPPER_INGOT);
        //items.add(Material.GLOW_BERRIES);
        //items.add(Material.GLOW_INK_SAC);
        //items.add(Material.RAW_COPPER);
        //items.add(Material.RAW_GOLD);
        //items.add(Material.RAW_IRON);
        //items.add(Material.SPYGLASS);
        //endregion
    }
}
